### ISSUE TITLE
Hint text and Featued Change

### ISSUE THREAD

**Issue by cnkygmr** [Flyclops/tenor_flutter#5]
Allowing to change hint text in Search and change Featued word in categories

**Comment by cnkygmr** [comment]
and can be when type search keywords after scroll keyboards dismiss like 
keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,

**Comment by LegendAF** [comment]
@cnkygmr It does seem like an oversight that you can't change `featured` in the categories. I will get an update out this weekend to address that.

**Comment by LegendAF** [comment]
> and can be when type search keywords after scroll keyboards dismiss like keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,

Can you explain this a little more or show me an example so I can get an idea of what functionality you are looking for?

**Comment by cnkygmr** [comment]
> > and can be when type search keywords after scroll keyboards dismiss like keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag,
> 
> Can you explain this a little more or show me an example so I can get an idea of what functionality you are looking for?

For example, when you search, the keyboard opens, then remains open while scrolling to see the gifs that appear in the search. All gifs are not visible in the ListView. When keyboardDismissBehavior: ScrollViewKeyboardDismissBehavior.onDrag, the keyboard closes while scrolling.

**Comment by cnkygmr** [comment]
@LegendAF  Also I think minExtent and maxExtent are not working either, for example I want it to open halfway when it first opens or it opens very long at a rate of 4 out of 10.

**Comment by cnkygmr** [comment]
Let me explain in more detail, I want to set the initial opening rate, if the user wants to see it longer, he can drag it to extend it.

**Comment by LegendAF** [comment]
This [PR](https://github.com/Flyclops/tenor_flutter/pull/4) addresses:
- search field being hard to localize
- featured category being impossible to localize
- adding `keyboardDismissBehavior` 

Can you file a bug ticket for the `minExtent` and `maxExtent` for me @cnkygmr?

**Comment by LegendAF** [comment]
v0.0.3 has been released

https://pub.dev/packages/tenor_flutter/changelog#003
