### ISSUE TITLE
Can be change DraggableScrollableSheet initialChildSize

### ISSUE THREAD

**Issue by cnkygmr** [Flyclops/tenor_flutter#6]
I want to adjust the height that comes at the beginning. The user can increase it if he wants. For example, if the maximum is 0.9, I want the length to come at the beginning as 0.4.

**Comment by cnkygmr** [comment]
Or we should be able to set all the values eğer biz bir değer vermezsek varsayılan olarak standart olan kullanılsın

```
      initialChildSize: maxChildSize,
      maxChildSize: maxChildSize,
      minChildSize: _sheetProvider.minExtent,
```

**Comment by LegendAF** [comment]
I'll dig into this as soon as I can this week. Thanks for the ticket!

**Comment by LegendAF** [comment]
@cnkygmr This turned out to be a bit bigger than expected. I have a path forward and I will have a PR up within the next couple days.

**Comment by LegendAF** [comment]
It has been a bit, but there is a [PR open](https://github.com/Flyclops/tenor_flutter/pull/8) to fix this
